name: Prettier Check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Check out the repository first.
      - uses: actionsx/prettier@v2
        with:
          # prettier CLI arguments.
          args: --check .
